version: '3.5'

services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db-server
    networks:
      - keycloak-network
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust

    ports:
      - 5000:5432

  keycloak-server:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak-server
    command: start-dev
    networks:
      - keycloak-network
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: ${KEYCLOAK_DB_NAME}
      DB_USER: ${KEYCLOAK_DB_USERNAME}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    depends_on:
      - keycloak-db
    ports:
      - 8000:8080

networks:
  keycloak-network:
    driver: bridge

volumes:
  pg_data:
