version: '3.5'

services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db-server
    networks:
      - keycloak-network
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

    ports:
      - 5000:5432

  keycloak-server:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak-server
    command: start-dev
    networks:
      - keycloak-network
    environment:
      - KEYCLOAK_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD
      - DB_VENDOR
      - DB_ADDR
      - DB_DATABASE
      - DB_USER
      - DB_PASSWORD
    depends_on:
      - keycloak-db
    ports:
      - 8000:8080

networks:
  keycloak-network:
    driver: bridge

volumes:
  pg_data:
